<a href="https://colab.research.google.com/github/sebakrys/data-science-bootcamp-A-Z/blob/main/01_numpy_pt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


[link text](https://)

### Basics

In [2]:
import numpy as np

np.__version__

'1.26.4'

In [3]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_core', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_ex

In [5]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

#### 1D Array

In [13]:
x= np.array([1, 2, 3])

In [14]:
x

array([1, 2, 3])

In [15]:
print(x)

[1 2 3]


In [16]:
type(x)

numpy.ndarray

number of dimensions


In [17]:
x.ndim

1

In [18]:
x.shape

(3,)

In [19]:
x.size

3

In [21]:
# data type in array
x.dtype

dtype('int64')

##### New Array

In [24]:
x = np.array([2.4, 2, 4.4, 6.2, 1.1])
print(x)
x.dtype

[2.4 2.  4.4 6.2 1.1]


dtype('float64')

#### 2d array

In [33]:
x= np.array([[1, 2, 3], [-1, -2, -3], [1.1, 2.2, 3.3]])
x

array([[ 1. ,  2. ,  3. ],
       [-1. , -2. , -3. ],
       [ 1.1,  2.2,  3.3]])

In [34]:
x.ndim

2

In [35]:
x.shape

(3, 3)

##### 2d array- 2 row, 3 collumns

In [37]:
x= np.array([[1, 2, 3],[-1, -2, -3]])
x

array([[ 1,  2,  3],
       [-1, -2, -3]])

In [38]:
x.shape

(2, 3)

#### 3d Array

In [49]:
x = np.array(
    [[[1, 2, 3],
     [-1, -2, -3]],

     [[1.1, 2.2, 3.3],
      [-1.1, -2.2, -3.3]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1.   2.   3. ]
  [-1.  -2.  -3. ]]

 [[ 1.1  2.2  3.3]
  [-1.1 -2.2 -3.3]]]
3
(2, 2, 3)


In [50]:
x = np.array(
    [[[1, 2, 3],
     [-1, -2, -3]],

     [[1.1, 2.2, 3.3],
      [-1.1, -2.2, -3.3]],

     [[1.1, 2.2, 3.3],
      [-1.1, -2.2, -3.3]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1.   2.   3. ]
  [-1.  -2.  -3. ]]

 [[ 1.1  2.2  3.3]
  [-1.1 -2.2 -3.3]]

 [[ 1.1  2.2  3.3]
  [-1.1 -2.2 -3.3]]]
3
(3, 2, 3)


In [52]:
x = np.array(
    [[[1],
     [-1]],

     [[1.1],
      [-1.1]],

     [[1.1],
      [-1.1]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1. ]
  [-1. ]]

 [[ 1.1]
  [-1.1]]

 [[ 1.1]
  [-1.1]]]
3
(3, 2, 1)


In [53]:
x = np.array(
    [[[1, 2, 3],
     [-1, -2, -3]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1  2  3]
  [-1 -2 -3]]]
3
(1, 2, 3)


### Data Types

In [55]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [56]:
A = np.array([1.1, 2.2, 3.3])
A.dtype

dtype('float64')

In [60]:
A = np.array([1, 2, 3], dtype="float")
print(A.dtype)
print(A)

float64
[1. 2. 3.]


In [61]:
A = np.array([1, 2, 3], dtype="complex")
print(A.dtype)

complex128


In [63]:
A = np.array([1.1, 2.2, 3.3], dtype="int")
print(A.dtype)
print(A)

int64
[1 2 3]


In [66]:
A = np.array([True, False])
print(A.dtype)

bool


In [68]:
A = np.array([63, 127, 255], dtype=np.int8)
print(A.dtype)
print(A)

int8
[ 63 127  -1]


<ipython-input-68-b415885924a7>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 255 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([63, 127, 255], dtype=np.int8)


In [69]:
A = np.array([63, 127, 255], dtype=np.uint8)
print(A.dtype)
print(A)

uint8
[ 63 127 255]
