<a href="https://colab.research.google.com/github/sebakrys/data-science-bootcamp-A-Z/blob/main/01_numpy_pt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Basics

In [ ]:
import numpy as np

np.__version__

'1.20.3'

In [ ]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

#### 1D Array

In [ ]:
x= np.array([1, 2, 3])

In [ ]:
x

array([1, 2, 3])

In [ ]:
print(x)

[1 2 3]


In [ ]:
type(x)

numpy.ndarray

number of dimensions


In [ ]:
x.ndim

1

In [ ]:
x.shape

(3,)

In [ ]:
x.size

3

In [ ]:
# data type in array
x.dtype

dtype('int32')

##### New Array

In [ ]:
x = np.array([2.4, 2, 4.4, 6.2, 1.1])
print(x)
x.dtype

[2.4 2.  4.4 6.2 1.1]


dtype('float64')

#### 2d array

In [ ]:
x= np.array([[1, 2, 3], [-1, -2, -3], [1.1, 2.2, 3.3]])
x

array([[ 1. ,  2. ,  3. ],
       [-1. , -2. , -3. ],
       [ 1.1,  2.2,  3.3]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(3, 3)

##### 2d array- 2 row, 3 collumns

In [ ]:
x= np.array([[1, 2, 3],[-1, -2, -3]])
x

array([[ 1,  2,  3],
       [-1, -2, -3]])

In [ ]:
x.shape

(2, 3)

#### 3d Array

In [ ]:
x = np.array(
    [[[1, 2, 3],
     [-1, -2, -3]],

     [[1.1, 2.2, 3.3],
      [-1.1, -2.2, -3.3]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1.   2.   3. ]
  [-1.  -2.  -3. ]]

 [[ 1.1  2.2  3.3]
  [-1.1 -2.2 -3.3]]]
3
(2, 2, 3)


In [ ]:
x = np.array(
    [[[1, 2, 3],
     [-1, -2, -3]],

     [[1.1, 2.2, 3.3],
      [-1.1, -2.2, -3.3]],

     [[1.1, 2.2, 3.3],
      [-1.1, -2.2, -3.3]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1.   2.   3. ]
  [-1.  -2.  -3. ]]

 [[ 1.1  2.2  3.3]
  [-1.1 -2.2 -3.3]]

 [[ 1.1  2.2  3.3]
  [-1.1 -2.2 -3.3]]]
3
(3, 2, 3)


In [ ]:
x = np.array(
    [[[1],
     [-1]],

     [[1.1],
      [-1.1]],

     [[1.1],
      [-1.1]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1. ]
  [-1. ]]

 [[ 1.1]
  [-1.1]]

 [[ 1.1]
  [-1.1]]]
3
(3, 2, 1)


In [ ]:
x = np.array(
    [[[1, 2, 3],
     [-1, -2, -3]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1  2  3]
  [-1 -2 -3]]]
3
(1, 2, 3)


### Data Types

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int32')

In [ ]:
A = np.array([1.1, 2.2, 3.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype="float")
print(A.dtype)
print(A)

float64
[1. 2. 3.]


In [ ]:
A = np.array([1, 2, 3], dtype="complex")
print(A.dtype)

complex128


In [ ]:
A = np.array([1.1, 2.2, 3.3], dtype="int")
print(A.dtype)
print(A)

int32
[1 2 3]


In [ ]:
A = np.array([True, False])
print(A.dtype)

bool


In [ ]:
A = np.array([63, 127, 255], dtype=np.int8)
print(A.dtype)
print(A)

int8
[ 63 127  -1]


In [ ]:
A = np.array([63, 127, 255], dtype=np.uint8)
print(A.dtype)
print(A)

uint8
[ 63 127 255]


### Creating Arrays


In [ ]:
np.zeros(shape=(4, 9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 9), dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(6, 6), dtype="int")

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(4, 4), fill_value=3, dtype="int")

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [ ]:
print(list(range(7)))
print(np.arange(7))

[0, 1, 2, 3, 4, 5, 6]
[0 1 2 3 4 5 6]


In [ ]:
np.arange(start=3, stop=11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(start=10, stop=110, step=10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.arange(start=110, stop=-110, step=-10)

array([ 110,  100,   90,   80,   70,   60,   50,   40,   30,   20,   10,
          0,  -10,  -20,  -30,  -40,  -50,  -60,  -70,  -80,  -90, -100])

In [ ]:
np.arange(start=0, stop=-1, step=-0.05)

array([ 0.  , -0.05, -0.1 , -0.15, -0.2 , -0.25, -0.3 , -0.35, -0.4 ,
       -0.45, -0.5 , -0.55, -0.6 , -0.65, -0.7 , -0.75, -0.8 , -0.85,
       -0.9 , -0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Basic Operation on Arrays

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


#### + - * /

In [ ]:
A + B

array([6, 0, 7, 4])

In [ ]:
A - B

array([0, 2, 1, 0])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 2

array([5, 3, 6, 4])

In [ ]:
2 * A

array([6, 2, 8, 4])

In [ ]:
A + 2*B

array([ 9, -1, 10,  6])

#### np.add, np.subtract, np.multiply, np.divide

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

#### Matrix multiply

In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, "\n")
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

### Pseudorandom number generator

In [ ]:
np.random.seed(0)

#### Normal distribution

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 5)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028, -0.89546656],
       [ 0.3869025 , -0.51080514, -1.18063218, -0.02818223,  0.42833187],
       [ 0.06651722,  0.3024719 , -0.63432209, -0.36274117, -0.67246045]])

#### Uniform distribution

In [ ]:
np.random.rand()

0.317983179393976

In [ ]:
np.random.rand(10)

array([0.41426299, 0.0641475 , 0.69247212, 0.56660145, 0.26538949,
       0.52324805, 0.09394051, 0.5759465 , 0.9292962 , 0.31856895])

In [ ]:
np.random.rand(5, 10)

array([[0.66741038, 0.13179786, 0.7163272 , 0.28940609, 0.18319136,
        0.58651293, 0.02010755, 0.82894003, 0.00469548, 0.67781654],
       [0.27000797, 0.73519402, 0.96218855, 0.24875314, 0.57615733,
        0.59204193, 0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782, 0.39650574,
        0.8811032 , 0.58127287, 0.88173536, 0.69253159, 0.72525428],
       [0.50132438, 0.95608363, 0.6439902 , 0.42385505, 0.60639321,
        0.0191932 , 0.30157482, 0.66017354, 0.29007761, 0.61801543],
       [0.4287687 , 0.13547406, 0.29828233, 0.56996491, 0.59087276,
        0.57432525, 0.65320082, 0.65210327, 0.43141844, 0.8965466 ]])

In [ ]:
np.random.randint(10)

6

In [ ]:
np.random.randint(low=10, high=100)

45

In [ ]:
np.random.choice([4, 2, 1, 3, 5])

3

In [ ]:
np.random.choice(["Asia", "Ala", "Ola"])

'Asia'

#### Array Shuffle

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([0, 2, 1, 8, 6, 4, 9, 5, 7, 3])

### Basic functions in numpy

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([2, 3, 55])

True

In [ ]:
np.all([2, 4, False])

False

In [ ]:
np.any([1, 2, 3, False])

True

In [ ]:
bool(0)

False

In [ ]:
A= np.random.rand(5)
A

array([0.85580334, 0.01171408, 0.35997806, 0.72999056, 0.17162968])

In [ ]:
np.argmax(A)

0

In [ ]:
A[np.argmax(A)]

0.855803342392611

In [ ]:
np.argmin(A)

1

In [ ]:
np.argsort(A)

array([1, 4, 2, 3, 0], dtype=int64)

In [ ]:
np.max(A)

0.855803342392611

In [ ]:
np.min(A)

0.011714084185001972

In [ ]:
np.mean(A)

0.4258231461482951

In [ ]:
np.median(A)

0.3599780644783639

In [ ]:
np.std(A)

0.32181889189143154

### Indexing and getting values from tables

In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [ ]:
A[2]

2

In [ ]:
A[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[[0, 2]]

array([0, 2])

In [ ]:
A[-1]

9

In [ ]:
A[3:7]

array([3, 4, 5, 6])

In [ ]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 77,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#getting column
print(A[:, 0])
print(A[:, -1])

[ 0  5 10 15]
[ 4  9 14 19]


In [ ]:
A[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [ ]:
A[1, 2] = 77
print(A)

[[ 0  1  2  3  4]
 [ 5  6 77  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### Interation over tables

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 77,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 77  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
    print(row[0:3])

[0 1 2]
[ 5  6 77]
[10 11 12]
[15 16 17]


In [ ]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
77
8
9
10
11
12
13
14
15
16
17
18
19


### changing size of Tables

In [ ]:
A.reshape(5, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 77],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 77,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 77, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### Logic Masks

In [ ]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
A[np.bitwise_or(A<-5,A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])