<a href="https://colab.research.google.com/github/sebakrys/data-science-bootcamp-A-Z/blob/main/01_numpy_pt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


[link text](https://)

### Basics

In [4]:
import numpy as np

np.__version__

'1.26.4'

In [3]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_core', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_ex

In [5]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

#### 1D Array

In [13]:
x= np.array([1, 2, 3])

In [14]:
x

array([1, 2, 3])

In [15]:
print(x)

[1 2 3]


In [16]:
type(x)

numpy.ndarray

number of dimensions


In [17]:
x.ndim

1

In [18]:
x.shape

(3,)

In [19]:
x.size

3

In [21]:
# data type in array
x.dtype

dtype('int64')

##### New Array

In [24]:
x = np.array([2.4, 2, 4.4, 6.2, 1.1])
print(x)
x.dtype

[2.4 2.  4.4 6.2 1.1]


dtype('float64')

#### 2d array

In [33]:
x= np.array([[1, 2, 3], [-1, -2, -3], [1.1, 2.2, 3.3]])
x

array([[ 1. ,  2. ,  3. ],
       [-1. , -2. , -3. ],
       [ 1.1,  2.2,  3.3]])

In [34]:
x.ndim

2

In [35]:
x.shape

(3, 3)

##### 2d array- 2 row, 3 collumns

In [37]:
x= np.array([[1, 2, 3],[-1, -2, -3]])
x

array([[ 1,  2,  3],
       [-1, -2, -3]])

In [38]:
x.shape

(2, 3)

#### 3d Array

In [49]:
x = np.array(
    [[[1, 2, 3],
     [-1, -2, -3]],

     [[1.1, 2.2, 3.3],
      [-1.1, -2.2, -3.3]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1.   2.   3. ]
  [-1.  -2.  -3. ]]

 [[ 1.1  2.2  3.3]
  [-1.1 -2.2 -3.3]]]
3
(2, 2, 3)


In [50]:
x = np.array(
    [[[1, 2, 3],
     [-1, -2, -3]],

     [[1.1, 2.2, 3.3],
      [-1.1, -2.2, -3.3]],

     [[1.1, 2.2, 3.3],
      [-1.1, -2.2, -3.3]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1.   2.   3. ]
  [-1.  -2.  -3. ]]

 [[ 1.1  2.2  3.3]
  [-1.1 -2.2 -3.3]]

 [[ 1.1  2.2  3.3]
  [-1.1 -2.2 -3.3]]]
3
(3, 2, 3)


In [52]:
x = np.array(
    [[[1],
     [-1]],

     [[1.1],
      [-1.1]],

     [[1.1],
      [-1.1]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1. ]
  [-1. ]]

 [[ 1.1]
  [-1.1]]

 [[ 1.1]
  [-1.1]]]
3
(3, 2, 1)


In [53]:
x = np.array(
    [[[1, 2, 3],
     [-1, -2, -3]]]
    )
print(x)
print(x.ndim)
print(x.shape)

[[[ 1  2  3]
  [-1 -2 -3]]]
3
(1, 2, 3)


### Data Types

In [55]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [56]:
A = np.array([1.1, 2.2, 3.3])
A.dtype

dtype('float64')

In [60]:
A = np.array([1, 2, 3], dtype="float")
print(A.dtype)
print(A)

float64
[1. 2. 3.]


In [61]:
A = np.array([1, 2, 3], dtype="complex")
print(A.dtype)

complex128


In [63]:
A = np.array([1.1, 2.2, 3.3], dtype="int")
print(A.dtype)
print(A)

int64
[1 2 3]


In [66]:
A = np.array([True, False])
print(A.dtype)

bool


In [68]:
A = np.array([63, 127, 255], dtype=np.int8)
print(A.dtype)
print(A)

int8
[ 63 127  -1]


<ipython-input-68-b415885924a7>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 255 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([63, 127, 255], dtype=np.int8)


In [69]:
A = np.array([63, 127, 255], dtype=np.uint8)
print(A.dtype)
print(A)

uint8
[ 63 127 255]


### Creating Arrays


In [70]:
np.zeros(shape=(4, 9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
np.zeros(shape=(4, 9), dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [73]:
np.ones(shape=(6, 6), dtype="int")

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [74]:
np.full(shape=(4, 4), fill_value=3, dtype="int")

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [79]:
print(list(range(7)))
print(np.arange(7))

[0, 1, 2, 3, 4, 5, 6]
[0 1 2 3 4 5 6]


In [81]:
np.arange(start=3, stop=11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
np.arange(start=10, stop=110, step=10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [87]:
np.arange(start=110, stop=-110, step=-10)

array([ 110,  100,   90,   80,   70,   60,   50,   40,   30,   20,   10,
          0,  -10,  -20,  -30,  -40,  -50,  -60,  -70,  -80,  -90, -100])

In [88]:
np.arange(start=0, stop=-1, step=-0.05)

array([ 0.  , -0.05, -0.1 , -0.15, -0.2 , -0.25, -0.3 , -0.35, -0.4 ,
       -0.45, -0.5 , -0.55, -0.6 , -0.65, -0.7 , -0.75, -0.8 , -0.85,
       -0.9 , -0.95])

In [92]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [97]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [99]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Basic Operation on Arrays

In [100]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


#### + - * /

In [101]:
A + B

array([6, 0, 7, 4])

In [102]:
A - B

array([0, 2, 1, 0])

In [103]:
A * B

array([ 9, -1, 12,  4])

In [105]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [106]:
A + 2

array([5, 3, 6, 4])

In [107]:
2 * A

array([6, 2, 8, 4])

In [113]:
A + 2*B

array([ 9, -1, 10,  6])

#### np.add, np.subtract, np.multiply, np.divide

In [108]:
np.add(A, B)

array([6, 0, 7, 4])

In [109]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [110]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [111]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

#### Matrix multiply

In [118]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, "\n")
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [119]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [120]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [122]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [121]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

### Pseudorandom number generator

In [5]:
np.random.seed(0)

#### Normal distribution

In [6]:
np.random.randn()

1.764052345967664

In [7]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [8]:
np.random.randn(10, 5)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028, -0.89546656],
       [ 0.3869025 , -0.51080514, -1.18063218, -0.02818223,  0.42833187],
       [ 0.06651722,  0.3024719 , -0.63432209, -0.36274117, -0.67246045]])

#### Uniform distribution

In [9]:
np.random.rand()

0.317983179393976

In [10]:
np.random.rand(10)

array([0.41426299, 0.0641475 , 0.69247212, 0.56660145, 0.26538949,
       0.52324805, 0.09394051, 0.5759465 , 0.9292962 , 0.31856895])

In [11]:
np.random.rand(5, 10)

array([[0.66741038, 0.13179786, 0.7163272 , 0.28940609, 0.18319136,
        0.58651293, 0.02010755, 0.82894003, 0.00469548, 0.67781654],
       [0.27000797, 0.73519402, 0.96218855, 0.24875314, 0.57615733,
        0.59204193, 0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782, 0.39650574,
        0.8811032 , 0.58127287, 0.88173536, 0.69253159, 0.72525428],
       [0.50132438, 0.95608363, 0.6439902 , 0.42385505, 0.60639321,
        0.0191932 , 0.30157482, 0.66017354, 0.29007761, 0.61801543],
       [0.4287687 , 0.13547406, 0.29828233, 0.56996491, 0.59087276,
        0.57432525, 0.65320082, 0.65210327, 0.43141844, 0.8965466 ]])

In [14]:
np.random.randint(10)

6

In [17]:
np.random.randint(low=10, high=100)

97

In [20]:
np.random.choice([4, 2, 1, 3, 5])

3

In [24]:
np.random.choice(["Asia", "Ala", "Ola"])

'Ola'

#### Array Shuffle

In [25]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.random.shuffle(data)
data

array([6, 1, 7, 3, 8, 5, 0, 9, 2, 4])