<a href="https://colab.research.google.com/github/sebakrys/data-science-bootcamp-A-Z/blob/main/02_numpy_pt2_linear_algebry.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra

In [2]:
import numpy as np
np.__version__

'1.26.4'

## Norm of vector in R2

In [3]:
v1= np.array([4, 9])
v1

array([4, 9])

In [4]:
np.linalg.norm(v1)

9.848857801796104

## Euclidan norm

In [5]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

## Distance between 2 points

In [6]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p-q)

5.0

In [7]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p-q)

5.0990195135927845

## Matrix multiplication

matrix (2, 5):
[
  [1, 2, 3, 4, 5],
  [1, 2, 3, 4, 5]
]

In [21]:
print(np.shape(np.array(
[
  [1, 2, 3, 4, 5],
  [1, 2, 3, 4, 5]
])))

(2, 5)


In [22]:
X = np.array(
    [[5, 3],
     [3, 9]]
    )
Y = np.array(
    [[1],
     [-1]]
    )
print(X,"\n", np.shape(X))
print(Y, np.shape(Y))

[[5 3]
 [3 9]] 
 (2, 2)
[[ 1]
 [-1]] (2, 1)


In [14]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [19]:
X = np.array(
    [
        [2, -1, 3],
        [3, 1, 0]
    ]
)
Y= np.array(
    [
        [2, 1, -1],
        [0, -1, 2],
        [3, 2, 0]
    ]
)
np.shape(X)

(2, 3)

In [18]:
np.dot(X, Y)

array([[13,  9],
       [ 6,  2]])

## Determinant

In [24]:
A = np.array(
    [
        [2, 4],
        [-1, 3]
    ]
)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))

9.999999999999998
10


## Matrix Trace - Ślad macierzy

In [25]:
np.trace(A)

5

## Identity matrix

In [26]:
np.eye(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Invertible matrix - macierz odwrotna

In [28]:
A = np.array(
    [
        [2, 4],
        [-1, 3]
    ]
)
B= np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [31]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [32]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

## Transpose matrix - Macierz transponowana

In [34]:
print(A)
print(np.transpose(A))

[[ 2  4]
 [-1  3]]
[[ 2 -1]
 [ 4  3]]


In [35]:
A.T

array([[ 2, -1],
       [ 4,  3]])

# Solving System of equations -  rozwiązywanie układów równań

X = A^(-1) B

In [36]:
A = np.array(
    [
        [2, 4],
        [1, -1]
    ]
)
B = np.array(
    [
        [10],
        [-1]
    ]
)

X = np.dot(np.linalg.inv(A), B)
print(X)

[[1.]
 [2.]]
