<a href="https://colab.research.google.com/github/sebakrys/data-science-bootcamp-A-Z/blob/main/02_numpy_pt2_linear_algebry.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra

In [2]:
import numpy as np
np.__version__

'1.26.4'

## Norm of vector in R2

In [3]:
v1= np.array([4, 9])
v1

array([4, 9])

In [4]:
np.linalg.norm(v1)

9.848857801796104

## Euclidan norm

In [5]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

## Distance between 2 points

In [6]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p-q)

5.0

In [7]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p-q)

5.0990195135927845

## Matrix multiplication

In [13]:
X = np.array(
    [[5, 3],
     [3, 9]]
    )
Y = np.array(
    [[1],
     [-1]]
    )
print(X,"\n", np.shape(X))
print(Y, np.shape(Y))

[[5 3]
 [3 9]] 
 (2, 2)
[[ 1]
 [-1]] (2, 1)


In [14]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [19]:
X = np.array(
    [
        [2, -1, 3],
        [3, 1, 0]
    ]
)
Y= np.array(
    [
        [2, 1, -1],
        [0, -1, 2],
        [3, 2, 0]
    ]
)
np.shape(X)

(2, 3)

In [18]:
np.dot(X, Y)

array([[13,  9],
       [ 6,  2]])

## Determinant