<a href="https://colab.research.google.com/github/sebakrys/data-science-bootcamp-A-Z/blob/main/03_numpy_pt3_Statistical_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Statistical functions

In [3]:
import numpy as np
np.__version__

'1.26.4'

In [15]:
price = np.array([
    [12.4, 12.8, 11.9, 12.6, 1000],
    [12.5, 13.00, 11.7, 12.2, 2000],
    [12.2, 13.4, 12.2, 13.2, 1500]
])
print(price, np.ndim(price))

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]] 2


## SUM

In [5]:
price.sum()

4650.1

In [6]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

## min

In [7]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

## max

In [8]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

## median

In [10]:
np.median(price)

12.6

## mean

In [11]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

## STD

In [13]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

## Var

In [14]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])