<a href="https://colab.research.google.com/github/sebakrys/data-science-bootcamp-A-Z/blob/main/31_s8_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


'2.17.1'

In [3]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

<Sequential name=sequential, built=False>


In [4]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


wyswietlenie podsumowania modelu

In [5]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 4)                   │              44 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:

model.add(Dense(units=2))

model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 4)                   │              44 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 2)                   │              10 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

#Funkcje aktywacji

###linear

In [7]:

from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

###sigmoid

In [8]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

###relu

In [9]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])


###tanh

In [10]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [11]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

#Kompilacja modelu

In [12]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:

**epochs** - krotność przejścia danych przez sieć w procesie uczenia
**batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
**validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
**validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [13]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

##Przykład - klasyfikacja binarna

In [14]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [15]:
data[:3]

array([[-1.73336697e+00, -3.52647077e-01,  1.68912902e+00,
        -3.58753547e-01, -1.68297049e-01,  8.06341083e-01,
        -1.03443412e+00, -2.56099273e+00, -4.81699168e-01,
        -1.84961787e+00,  1.18522920e+00,  4.62534634e-01,
        -7.93827234e-01,  1.63901565e+00,  1.41737392e+00,
         4.17081584e-02, -7.61736164e-02, -7.89363849e-01,
        -7.32110680e-02, -6.17659033e-01,  6.83048290e-01,
         1.26487841e+00, -1.59244884e-01, -2.42434125e-01,
         6.87051691e-01, -1.31328429e-01, -6.82295084e-01,
         1.30309679e+00,  2.91193283e-01, -2.42713779e-01,
        -1.35798390e+00,  1.68321405e-01, -7.10135402e-01,
        -2.84206692e-02,  4.72200891e-01, -1.49964064e-01,
        -2.16644091e-02, -1.85316844e+00,  8.07423934e-01,
         1.26107558e-01, -1.88573070e-01, -2.06460425e-01,
        -1.00019534e+00, -3.52962801e-02,  7.40464482e-01,
         9.75817206e-01, -1.91675047e+00,  1.01622288e+00,
         4.94359350e-01,  9.61858754e-01,  8.06638092e-0

In [16]:
labels[:10]

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0]])

In [17]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5048 - loss: 0.7834
Epoch 2/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5415 - loss: 0.6939
Epoch 3/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5717 - loss: 0.6725
Epoch 4/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6026 - loss: 0.6610
Epoch 5/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6217 - loss: 0.6501
Epoch 6/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6469 - loss: 0.6347
Epoch 7/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6664 - loss: 0.6212
Epoch 8/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6771 - loss: 0.6085
Epoch 9/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6953 - loss: 0.5931
Epoch 10/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7048 - loss: 0.5800
Epoch 11/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7178 - loss: 0.5661
Epoch 12/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [18]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4962 - loss: 0.7892
Epoch 2/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5286 - loss: 0.7049
Epoch 3/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5617 - loss: 0.6838
Epoch 4/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5998 - loss: 0.6668
Epoch 5/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6099 - loss: 0.6563
Epoch 6/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6293 - loss: 0.6449
Epoch 7/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6443 - loss: 0.6344
Epoch 8/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6585 - loss: 0.6249
Epoch 9/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6757 - loss: 0.6133
Epoch 10/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6897 - loss: 0.6016
Epoch 11/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6961 - loss: 0.5935
Epoch 12/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [19]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [20]:

metrics = history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [21]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4836 - loss: 0.7962 - val_accuracy: 0.4930 - val_loss: 0.7270
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5446 - loss: 0.6961 - val_accuracy: 0.4965 - val_loss: 0.7204
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5837 - loss: 0.6696 - val_accuracy: 0.4985 - val_loss: 0.7208
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6169 - loss: 0.6565 - val_accuracy: 0.4970 - val_loss: 0.7227
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6346 - loss: 0.6410 - val_accuracy: 0.4995 - val_loss: 0.7284
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6650 - loss: 0.6199 - val_accuracy: 0.4935 - val_loss: 0.7316
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6811 - loss: 0.6058 - val_accuracy: 0.4990 - val_loss: 0.7395
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7095 - loss: 0.5866 - val_accuracy: 0.

In [22]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [23]:
predictions = model.predict(test_data)
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


array([[0.9238079 ],
       [0.01609849],
       [0.7694204 ],
       [0.8930259 ],
       [0.15006241]], dtype=float32)

In [24]:
probabilities = predictions
print("Predictions:", predictions)
print("Probabilities:", probabilities)

Predictions: [[0.9238079 ]
 [0.01609849]
 [0.7694204 ]
 [0.8930259 ]
 [0.15006241]]
Probabilities: [[0.9238079 ]
 [0.01609849]
 [0.7694204 ]
 [0.8930259 ]
 [0.15006241]]


In [25]:
predictions = model.predict(test_data)
predicted_classes = (predictions > 0.5).astype(int) # Convert probabilities to class labels (0 or 1)
print("Predicted Classes:", predicted_classes)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
Predicted Classes: [[1]
 [0]
 [1]
 [1]
 [0]]


#Przykład - klasyfikacja wieloklasowa

In [27]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

In [28]:
print(data.shape)
print(labels.shape)


(10000, 150)
(10000, 1)


In [29]:
labels[:10]

array([[2],
       [3],
       [4],
       [2],
       [1],
       [1],
       [8],
       [6],
       [5],
       [4]])

In [30]:

from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels


array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [31]:
labels[1]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [32]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1100 - loss: 2.3320 - val_accuracy: 0.0995 - val_loss: 2.3036
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1008 - loss: 2.3029 - val_accuracy: 0.0905 - val_loss: 2.3103
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1141 - loss: 2.3003 - val_accuracy: 0.0925 - val_loss: 2.3114
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1189 - loss: 2.2977 - val_accuracy: 0.0930 - val_loss: 2.3122
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1142 - loss: 2.2952 - val_accuracy: 0.0935 - val_loss: 2.3241
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1178 - loss: 2.2920 - val_accuracy: 0.0965 - val_loss: 2.3190
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1261 - loss: 2.2855 - val_accuracy: 0.0900 - val_loss: 2.3187
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1334 - loss: 2.2809 - val_accuracy: 0.

In [33]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[0.05163549, 0.03620753, 0.19488797, 0.11605001, 0.11460435,
        0.11857633, 0.033359  , 0.04017619, 0.0798472 , 0.21465586],
       [0.03144349, 0.16326718, 0.07939494, 0.12560266, 0.10737916,
        0.12750663, 0.14623004, 0.06846336, 0.04557165, 0.10514081],
       [0.14049499, 0.15859745, 0.11629424, 0.05112705, 0.08838393,
        0.02972856, 0.07401346, 0.14205034, 0.08598448, 0.11332546],
       [0.07276675, 0.09137708, 0.21036248, 0.099319  , 0.05154478,
        0.06504954, 0.08871057, 0.12047655, 0.10355465, 0.09683857],
       [0.08959096, 0.07892779, 0.11756819, 0.12493501, 0.08676753,
        0.11077349, 0.1146385 , 0.09443727, 0.0933205 , 0.08904069],
       [0.1140402 , 0.0722723 , 0.11599316, 0.09830825, 0.11360503,
        0.09809379, 0.09625843, 0.08025792, 0.11910854, 0.09206239],
       [0.14623657, 0.06779739, 0.12287264, 0.02310065, 0.16855896,
        0.13798101, 0.02721369, 0.0781147 , 0.06976397, 0.15836059],
       [0.10998116, 0.08604074, 0.1089107

In [35]:
#model.predict_classes(test_data)
predictions = model.predict(test_data)
predicted_classes = np.argmax(predictions, axis=1)
print("Predicted Classes:", predicted_classes)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
Predicted Classes: [9 1 1 2 3 8 4 8 5 7]


#Przykład - regresja

In [36]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [37]:

labels[:10]

array([30.90396467,  1.58978363, 29.51054701, 33.5704893 , 45.67873465,
       13.76530015, 38.12950154, 29.50999932, 32.52750698, 24.32794465])

In [38]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 426.5033 - val_loss: 208.8650
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 214.7204 - val_loss: 207.4447
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 213.5173 - val_loss: 207.9321
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 209.9015 - val_loss: 207.1800
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 211.4576 - val_loss: 206.9659
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 208.1705 - val_loss: 207.1117
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 209.4649 - val_loss: 207.1766
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 212.4404 - val_loss: 208.8623
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 209.1814 - val_loss: 207.0656
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 209.3952 - val_loss: 207.1375
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 211.0480 - val_loss: 207.3543
Epoch 12/30
250/250

In [39]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 15.7919 - mse: 369.1259 - val_loss: 12.4655 - val_mse: 208.0698
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.6039 - mse: 212.1903 - val_loss: 12.4502 - val_mse: 207.0733
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5708 - mse: 211.5029 - val_loss: 12.4526 - val_mse: 206.7946
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.6560 - mse: 213.6300 - val_loss: 12.4568 - val_mse: 206.8710
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.6802 - mse: 214.8092 - val_loss: 12.4915 - val_mse: 208.3268
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.7058 - mse: 215.6308 - val_loss: 12.5073 - val_mse: 210.8794
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.6673 - mse: 214.3092 - val_loss: 12.4944 - val_mse: 208.6057
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5638 - mse: 211.2708 - val_loss: 12.4554 - val_mse: 207.4932
Epoch 9/

In [40]:

test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


array([[21.87325 ],
       [23.915009],
       [23.38896 ],
       [27.286709],
       [22.47245 ],
       [24.182442],
       [27.758516],
       [24.656855],
       [21.903849],
       [25.712736]], dtype=float32)